In [1]:
a = [],
     [7, 8, 9]][1, 2, 3],
     [4, 5, 6
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [2]:
def print_matrix(m):
    for row in m:
        print(row)

In [3]:
print_matrix(a)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [4]:
r = a[1]
print(r)

[4, 5, 6]


In [6]:
m1 = a[1:]
print_matrix(m1)

[4, 5, 6]
[7, 8, 9]


In [8]:
import random as rd
a = [list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5)),
     list(rd.sample(range(10, 100), 5))]

In [9]:
print_matrix(a)

[11, 47, 36, 25, 42]
[10, 22, 68, 35, 59]
[88, 90, 19, 96, 21]
[96, 83, 13, 70, 60]
[98, 36, 58, 17, 81]


In [11]:
middle = a[1:4]
print_matrix(middle)
middle = a[-4:-1]
print_matrix(middle)
middle = a[1:-1]
print_matrix(middle)
middle = a[-4:4]
print_matrix(middle)

[10, 22, 68, 35, 59]
[88, 90, 19, 96, 21]
[96, 83, 13, 70, 60]
[10, 22, 68, 35, 59]
[88, 90, 19, 96, 21]
[96, 83, 13, 70, 60]
[10, 22, 68, 35, 59]
[88, 90, 19, 96, 21]
[96, 83, 13, 70, 60]
[10, 22, 68, 35, 59]
[88, 90, 19, 96, 21]
[96, 83, 13, 70, 60]


In [13]:
last_rows = a[3:5]
print_matrix(last_rows)
last_rows = a[3:]
print_matrix(last_rows)
last_rows = a[-2:]
print_matrix(last_rows)
last_rows = a[-2:5]
print_matrix(last_rows)

[96, 83, 13, 70, 60]
[98, 36, 58, 17, 81]
[96, 83, 13, 70, 60]
[98, 36, 58, 17, 81]
[96, 83, 13, 70, 60]
[98, 36, 58, 17, 81]
[96, 83, 13, 70, 60]
[98, 36, 58, 17, 81]


In [22]:
n = int(input('Enter n: '))
if -len(a) <= n < len(a):
    min_nrow = min(a[n])
    max_nrow = max(a[n])
    sum_nrow = sum(a[n])
    sorted_nrow = sorted(a[n])
    print('Min of a[{0}] = {1}'.format(n, min_nrow))
    print('Max of a[{0}] = {1}'.format(n, max_nrow))
    print('Sum of a[{0}] = {1}'.format(n, sum_nrow))
    print('Sort of a[{0}] = {1}'.format(n, sorted_nrow))
else:
    print('Invalid n')

Min of a[3] = 13
Max of a[3] = 96
Sum of a[3] = 322
Sort of a[3] = [13, 60, 70, 83, 96]


In [24]:
a = [4, 9, 10, 2, 0]
b = sorted(a)
print(a, b, sep='\n')
a.sort()
print(a)

[4, 9, 10, 2, 0]
[0, 2, 4, 9, 10]
[0, 2, 4, 9, 10]


In [25]:
b = sorted(a, reverse=True)
print(b)

[10, 9, 4, 2, 0]


In [27]:
names = ['John Lennon', 'Demba Ba', 'Mike Tyson', 'Paul McCarteney', 'Cong Tang Ton Nu Nguyen Thi Huong']

In [29]:
print(min(names))
print(max(names))

Cong Tang Ton Nu Nguyen Thi Huong
Paul McCarteney


In [30]:
print(min(names, key=len))
print(max(names, key=len))

Demba Ba
Cong Tang Ton Nu Nguyen Thi Huong


In [32]:
print(sorted(names, key=len, reverse=True))

['Cong Tang Ton Nu Nguyen Thi Huong', 'Paul McCarteney', 'John Lennon', 'Mike Tyson', 'Demba Ba']


In [33]:
import numpy as np

In [34]:
print(a, type(a))

[0, 2, 4, 9, 10] <class 'list'>


In [35]:
a = np.array(a)
print(a, type(a))

[ 0  2  4  9 10] <class 'numpy.ndarray'>


In [37]:
numbers = np.linspace(1, 10, 10, dtype=int)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
odds = np.linspace(1, 9, 5, dtype=int)
print(odds)
evens = np.linspace(0, 10, 6, dtype=int)
print(evens)

[1 3 5 7 9]
[ 0  2  4  6  8 10]


In [46]:
floats = np.linspace(0, 1, 50, endpoint=False)
print(floats)

[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2  0.22 0.24 0.26
 0.28 0.3  0.32 0.34 0.36 0.38 0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54
 0.56 0.58 0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78 0.8  0.82
 0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98]


In [48]:
numbers = np.linspace(0, 10, 10)
print(numbers)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [49]:
numbers = np.linspace(0, 10, 10, endpoint=False)
print(numbers)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [52]:
numbers = np.logspace(0, 10, 10, endpoint=False)
print(numbers)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]


In [53]:
a = list(range(1, 10))
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [54]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [55]:
odds = np.arange(1, 10, 2)
print(odds)

[1 3 5 7 9]


In [56]:
evens = np.arange(0, 10, 2)
print(evens)

[0 2 4 6 8]


In [57]:
numbers = np.arange(0, 1, 0.02)
print(numbers)

[0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2  0.22 0.24 0.26
 0.28 0.3  0.32 0.34 0.36 0.38 0.4  0.42 0.44 0.46 0.48 0.5  0.52 0.54
 0.56 0.58 0.6  0.62 0.64 0.66 0.68 0.7  0.72 0.74 0.76 0.78 0.8  0.82
 0.84 0.86 0.88 0.9  0.92 0.94 0.96 0.98]


In [58]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
b = np.ones(10, dtype=int)
print(b)

[1 1 1 1 1 1 1 1 1 1]


In [61]:
a = np.array([1, 2, 3, 4])
b = np.ones(4)
c = a + b
print(c)

[2. 3. 4. 5.]


In [62]:
d = c * 2
print(d)

[ 4.  6.  8. 10.]


In [63]:
e = c * d
print(e)

[ 8. 18. 32. 50.]


In [64]:
f = e / 2
print(f)

[ 4.  9. 16. 25.]


In [67]:
numbers = np.arange(0, 1, 0.1)
print(numbers)
sin_numbers = np.sin(numbers)
print(sin_numbers)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]


In [71]:
numbers = np.random.randint(1, 100, 20)
print(numbers)

[61 74 56 89 23 29 86 74 13 51 14 61 89 27 22 86 10 24 64 76]


In [72]:
odd_index = numbers % 2 == 1
print(odd_index)

[ True False False  True  True  True False False  True  True False  True
  True  True False False False False False False]


In [73]:
odds = numbers[odd_index] # numbers[numbers%2==1]
print(odds)

[61 89 23 29 13 51 61 89 27]


In [74]:
evens = numbers[numbers%2==0]
print(evens)

[74 56 86 74 14 22 86 10 24 64 76]


In [75]:
a = numbers[numbers>50]
print(a)

[61 74 56 89 86 74 51 61 89 86 64 76]


In [78]:
numbers[numbers%2==1]=1
print(numbers)
numbers[numbers%2==0]=0
print(numbers)

[ 1 74 56  1  1  1 86 74  1  1 14  1  1  1 22 86 10 24 64 76]
[1 0 0 1 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 0]


In [82]:
genders = np.array(['Male', 'Female', 'Female', 'Female', 'Male', 'Male'])
print(genders)
genders[genders=='Male'] = 'M'
print(genders)
genders[genders=='Female'] = 'F'
print(genders)

['Male' 'Female' 'Female' 'Female' 'Male' 'Male']
['M' 'Female' 'Female' 'Female' 'M' 'M']
['M' 'F' 'F' 'F' 'M' 'M']


In [83]:
numbers = np.random.randint(10, 100, 20)
print(numbers)

[31 25 94 40 83 98 41 58 61 64 12 53 19 97 36 13 94 66 51 94]


In [84]:
evens = numbers[numbers%2==0]
evens.sort()
print(evens)

[12 36 40 58 64 66 94 94 94 98]


In [85]:
odds = numbers[numbers%2==1]
odds.sort()
numbers = np.concatenate((evens, odds))
print(numbers)

[12 36 40 58 64 66 94 94 94 98 13 19 25 31 41 51 53 61 83 97]
