In [1]:
import numpy as np
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2]) 
# Calculate v

In [2]:
v = np.zeros(7)
i = 1

while i < len(y):
    v[i] = (y[i] - y[i-1]) / (t[i] - t[i-1])
    i += 1

print(v)

[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [3]:
print((y[1:] - y[:-1])/(t[1:] - t[:-1]))


[ 2.65306122  7.25490196 11.8        13.79310345 20.85106383 17.38461538]


In [6]:
names = np.array(['John Lennon', 'Mike Tyson', 'Duong Van Linh', 'Hoang', '', '', 'Paul'])
names[names == ''] = 'John Doe'
print(names)

['John Lennon' 'Mike Tyson' 'Duong Van Linh' 'Hoang' 'John Doe' 'John Doe'
 'Paul']


In [7]:
ages = np.array([-10, 28, 38, 189, 0, 22])
ages[ages<0] = 0
ages[ages>150] = 150
print(ages)

[  0  28  38 150   0  22]


In [8]:
min_age = min(ages)
max_age = max(ages)
print('Min age:', min_age)
print('Max age:', max_age)

Min age: 0
Max age: 150


In [11]:
longest_name = max(names, key=len)
shortest_name = min(names, key=len)
print('Longest name:', longest_name)
print('Shortest name:', shortest_name)

Longest name: Duong Van Linh
Shortest name: Paul


In [13]:
len_names = [len(n) for n in names] # list comprehension
print(len_names)
print(max(len_names))
print(min(len_names))

[11, 10, 14, 5, 8, 8, 4]
14
4


In [15]:
# create 2d arrays
a = np.zeros((5, 5), dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [18]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[list([1, 2, 3]) list([4, 5, 6, 5])]


<ipython-input-18-1af537f5e0d5>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1, 2, 3], [4, 5, 6, 5]])


In [20]:
a = [1, 2, 3, 4, 5, 6] # 1d list
a = np.reshape(a, (3, 2))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
# create array of random numbers
a = np.random.randint(-99, 100, (8, 8))
print(a)

[[-96  -1  -3  89 -12  53  35  91]
 [ 10 -18  34  49 -71  81 -43  93]
 [ 41 -75 -23 -79  22  10 -55  14]
 [  9 -43  73   5 -69  -7  -7 -49]
 [ 87 -50 -56  -7 -66  93 -53 -79]
 [-83  96  57  91  71 -68  33 -45]
 [-79  15   6 -91  55 -14 -14  52]
 [-31  18  27  76  65 -49   5  15]]


In [22]:
print(a[2:5])

[[ 41 -75 -23 -79  22  10 -55  14]
 [  9 -43  73   5 -69  -7  -7 -49]
 [ 87 -50 -56  -7 -66  93 -53 -79]]


In [25]:
print(a[6:], a[-2:], sep='\n\n')

[[-79  15   6 -91  55 -14 -14  52]
 [-31  18  27  76  65 -49   5  15]]

[[-79  15   6 -91  55 -14 -14  52]
 [-31  18  27  76  65 -49   5  15]]


In [27]:
# a.1
a = np.zeros((8, 8), dtype=int)
a[0] = 1      # 1st row
a[-1] = 1     # last row
a[:, 0] = 1   # 1st column
a[:, -1] = 1  # last column
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [28]:
# a.2
a = np.ones((8, 8), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
