In [ ]:
# for (i = 0; i < n; i++)

In [ ]:
for i in range(0, 10):
    print(i)

In [ ]:
# foreach  (Object o in listObjects)

In [4]:
names = ["John", "Bob", "Mary"]
for n in names:
    print(n)

John
Bob
Mary


In [6]:
n = int(input("Enter a n: "))
for i in range(0, n):
    for j in range(0, i + 1):
        print("*", end="")
    print()

*
**
***
****
*****


In [8]:
rooms = {'John':400, 'Mike':431, 'Obama':382, 'Linda':102}
for k, v in rooms.items():
    print('{0} stays in room {1}'.format(k, v))

John stays in room 400
Mike stays in room 431
Obama stays in room 382
Linda stays in room 102


In [11]:
msg = "Hello World"
for c in msg:
    if c in 'aeiou':
        print(c, end="*")

e*o*o*

In [19]:
# List comprehension
names = ["John", "Bob", "Mary"]
names_len = [len(n) for n in names]
print(names, names_len)

['John', 'Bob', 'Mary'] [4, 3, 4]


In [21]:
import numpy as np
numbers = np.random.randint(0, 100, 20)
print(numbers)

[96 41 62 35 41 99 52 69 45 71 49  5 72 10 13 59  8 20 81 13]


In [22]:
evens = numbers[numbers % 2 == 0]
print(evens)

[96 62 52 72 10  8 20]


In [24]:
import random as rd
numbers = rd.sample(range(0, 100), 20)
print(numbers)
evens = [n for n in numbers if n % 2 == 0]
print(evens)

[84, 67, 62, 87, 68, 24, 35, 21, 51, 14, 33, 40, 30, 16, 12, 45, 31, 94, 27, 2]
[84, 62, 68, 24, 14, 40, 30, 16, 12, 94, 2]


In [25]:
numbers = np.random.randint(-100, 100, 20)
# Filter positive numbers using boolean indexing and list comprehension
positives = numbers[numbers > 0]
print(positives)
positives = [n for n in numbers if n > 0]
print(positives)

[25 43 20 21 78 73 63 75 69 63 95 85 32]
[25, 43, 20, 21, 78, 73, 63, 75, 69, 63, 95, 85, 32]


In [27]:
names = ['John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Starr',
         'Pete Best', 'Stuart Sutcliffe']
# Find names which len <= 10
short_names = [n for n in names if len(n) <= 11]
print(short_names)

['John Lennon', 'Ringo Starr', 'Pete Best']


In [28]:
print(numbers)

[ -17   25   43   20   21   78 -100   73   63   75  -55   69   63   95
   85  -61   32  -61  -56  -73]


In [29]:
# Convert positive numbers to 1, negative numbers to 0
new_numbers = [1 if n > 0 else 0 for n in numbers]
print(new_numbers)

[0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0]


In [30]:
# Convert long names to 'John Doe' (len > 11)
convert_names = ['John Doe' if len(n) > 11 else n for n in names]
print(convert_names)

['John Lennon', 'John Doe', 'John Doe', 'Ringo Starr', 'Pete Best', 'John Doe']


In [31]:
matrix = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
# Get diagonal elements
diagonal = [matrix[i][i] for i in range(len(matrix))]
print(diagonal)

[1, 6, 11, 16]


In [32]:
n = len(matrix)
reversed_diagonal = [matrix[i][n - i - 1] for i in range(n)]
print(reversed_diagonal)

[4, 7, 10, 13]
